name: brandon-syiem
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "contrast" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-target-blank


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      author_profile: true

author:
  name: "Brandon Syiem"
  avatar: "assets/images/brandon.jpg"
  location: "Sydney, New South Wales"
  links:
    - label: "Email"
      url: "mailto:brandon.syiem@sydney.edu.au"
    - label: "Scholar"
      url: "https://scholar.google.com/citations?user=NLv_1gMAAAAJ&hl=en"
